DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id VARCHAR(250)  PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL
);

